(function () {
  const STORAGE_KEY = 'bitHappenPlanCards_v1';

  const defaultCards = [
    {
      id: 'kiosk-daiso',
      group: 'kiosk',
      badge: 'Kiosk',
      title: '다이소 상품 위치 안내',
      copy: '대형 매장 내 위치 탐색과 경로 안내를 직관적으로 제공합니다.',
      features: ['상품 탐색 UI', '층별/구역별 경로 안내', '매장 운영 효율 개선'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 10,
      span: 1,
      industry: '리테일',
      period: '4-8주 파일럿',
      integration: '매장 DB, 안내 단말',
      tags: ['On-site UX', 'Navigation', 'Retail'],
    },
    {
      id: 'kiosk-retail3',
      group: 'kiosk',
      badge: 'Kiosk',
      title: '유통 3사 통합 안내 시스템',
      copy: '롯데/신세계/현대 등 복합 유통 환경에 맞춘 통합 안내 솔루션입니다.',
      features: ['브랜드 통합 UX', '지점별 커스터마이징', '확장형 운영 구조'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 20,
      span: 1,
      industry: '유통',
      period: '6-10주 구축',
      integration: 'CMS, 지점 시스템',
      tags: ['Multi-brand', 'CMS', 'Guide'],
    },
    {
      id: 'kiosk-mma',
      group: 'kiosk',
      badge: 'Kiosk',
      title: '전국 병무청 판정검사 키오스크',
      copy: '공공기관 업무 흐름에 맞춘 민원/검사 프로세스를 자동화합니다.',
      features: ['신원 확인 절차', '대기 동선 최적화', '안정적 현장 운영'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 30,
      span: 1,
      industry: '공공기관',
      period: '8-12주 구축',
      integration: '본인인증, 민원 백오피스',
      tags: ['Public', 'Queue', 'Kiosk'],
    },
    {
      id: 'kiosk-shelter',
      group: 'kiosk',
      badge: 'Kiosk',
      title: '전국 스마트 쉘터 정보 시스템',
      copy: '공공 쉘터 정보, 위치, 상태를 실시간으로 안내합니다.',
      features: ['실시간 상태 표시', '위치 기반 탐색', '중앙 관제 연계'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 40,
      span: 1,
      industry: '공공 인프라',
      period: '6-9주 구축',
      integration: '관제 서버, IoT 상태 데이터',
      tags: ['Shelter', 'Realtime', 'Public'],
    },
    {
      id: 'kiosk-barrierfree',
      group: 'kiosk',
      badge: 'Kiosk',
      title: '비접촉 배리어프리 키오스크',
      copy: '접근성 특화 인터페이스로 누구나 쉽게 사용할 수 있는 키오스크를 제공합니다.',
      features: ['비접촉 상호작용', '접근성 강화 UI', '공공/의료 적용'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 50,
      span: 1,
      industry: '의료, 공공',
      period: '4-8주 구축',
      integration: '접근성 장치, 운영 CMS',
      tags: ['Accessibility', 'Touchless', 'Inclusive'],
    },
    {
      id: 'kiosk-restroom',
      group: 'kiosk',
      badge: 'Kiosk',
      title: '스마트 화장실 안내 솔루션',
      copy: '시설 상태와 위치 정보를 통합해 이용 편의성을 높입니다.',
      features: ['혼잡도 정보', '시설 상태 안내', '운영 효율 분석'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 60,
      span: 1,
      industry: '공공시설',
      period: '3-6주 구축',
      integration: '센서 데이터, 안내 단말',
      tags: ['Facility', 'Crowd', 'Guide'],
    },
    {
      id: 'kiosk-ssino',
      group: 'kiosk',
      badge: 'Kiosk',
      title: 'SSINO POS/CMS',
      copy: '매장 운영, 콘텐츠, 결제를 통합 관리하는 플랫폼입니다.',
      features: ['POS 연동', 'CMS 중앙 관리', '다지점 운영 지원'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 70,
      span: 1,
      industry: '리테일, 외식',
      period: '4-7주 구축',
      integration: 'POS, 결제, 운영 백오피스',
      tags: ['POS', 'CMS', 'Multi-store'],
    },
    {
      id: 'kiosk-evanpos',
      group: 'kiosk',
      badge: 'Kiosk',
      title: 'EvanPOS 레스토랑 관리',
      copy: '외식 매장의 주문, 결제, 운영 데이터를 통합 관리합니다.',
      features: ['주문/결제 통합', '메뉴/재고 관리', '매장 성과 분석'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 80,
      span: 1,
      industry: '외식',
      period: '3-6주 구축',
      integration: 'POS, 주방 시스템, 결제 모듈',
      tags: ['Restaurant', 'POS', 'Analytics'],
    },
    {
      id: 'kiosk-smart-kiosk-platform',
      group: 'kiosk',
      badge: 'Kiosk',
      title: '스마트 키오스크 플랫폼',
      copy: '안내, 주문, 발권, 민원 처리를 통합하는 범용 키오스크 플랫폼입니다.',
      features: ['업종별 UI 템플릿', '단말 통합 관리', '운영 데이터 리포팅'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 82,
      span: 2,
      industry: '리테일, 공공, 서비스',
      period: '4-8주 구축',
      integration: '키오스크 단말, CMS, 결제 모듈',
      tags: ['Kiosk Platform', 'Template', 'Operations'],
    },
    {
      id: 'kiosk-face-delivery',
      group: 'kiosk',
      badge: 'Kiosk',
      title: '얼굴 인식 배송 키오스크',
      copy: '얼굴 인식 기반 본인 확인으로 무인 배송/수령을 처리하는 키오스크입니다.',
      features: ['얼굴 인증 수령', '무인 보관함 연동', '수령 이력 추적'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 84,
      span: 1,
      industry: '라스트마일, 유통',
      period: '5-8주 구축',
      integration: '카메라, 인증 서버, 보관함 제어',
      tags: ['Face ID', 'Delivery', 'Unmanned'],
    },
    {
      id: 'kiosk-unmanned-pickup',
      group: 'kiosk',
      badge: 'Kiosk',
      title: '무인 배송/수령 시스템',
      copy: '배송 상태 조회부터 무인 수령까지 통합 관리하는 운영 시스템입니다.',
      features: ['배송 상태 연동', '수령 인증 처리', '운영 알림 자동화'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 86,
      span: 1,
      industry: '물류, 이커머스',
      period: '4-7주 구축',
      integration: '택배/물류 API, 인증 모듈',
      tags: ['Logistics', 'Pickup', 'Automation'],
    },
    {
      id: 'kiosk-pet-kiosk',
      group: 'kiosk',
      badge: 'Kiosk',
      title: '반려동물 키오스크',
      copy: '반려동물 서비스 현장에 특화된 무인 접수/결제 키오스크 솔루션입니다.',
      features: ['서비스 접수 자동화', '보호자 인증/결제', '운영 대시보드'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 88,
      span: 1,
      industry: '펫케어, 리테일',
      period: '3-6주 구축',
      integration: 'POS, 예약 시스템, 결제',
      tags: ['Pet', 'Self-service', 'Kiosk'],
    },
    {
      id: 'kiosk-pos-cms-system',
      group: 'kiosk',
      badge: 'Kiosk',
      title: 'POS CMS 시스템',
      copy: '키오스크 운영 현장을 위한 POS/CMS 통합 운영 시스템입니다.',
      features: ['주문/결제 데이터 통합', '콘텐츠 중앙 배포', '매장별 운영 제어'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 89,
      span: 1,
      industry: '리테일, 외식',
      period: '4-8주 구축',
      integration: 'POS, CMS, ERP',
      tags: ['POS', 'CMS', 'Control'],
    },
    {
      id: 'ai-quickclip',
      group: 'ai',
      badge: 'AI',
      title: 'QuickClip',
      copy: '주제 입력만으로 영상 제작 파이프라인을 자동화합니다.',
      features: ['원클릭 영상 생성', '자동 편집 워크플로우', '운영 효율 향상'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 90,
      span: 2,
      industry: '미디어, 마케팅',
      period: '3-5주 적용',
      integration: '콘텐츠 저장소, 배포 API',
      tags: ['GenAI', 'Video', 'Automation'],
    },
    {
      id: 'ai-synopsis',
      group: 'ai',
      badge: 'AI',
      title: 'Synopsis ToScreenplay',
      copy: '시놉시스에서 각본까지 연결되는 생성형 파이프라인입니다.',
      features: ['스토리 구조 생성', '각본 자동 확장', '콘텐츠 제작 가속'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 100,
      span: 1,
      industry: '콘텐츠',
      period: '2-4주 적용',
      integration: '문서 협업 도구, LLM API',
      tags: ['LLM', 'Script', 'Pipeline'],
    },
    {
      id: 'ai-smartface',
      group: 'ai',
      badge: 'AI',
      title: 'SmartFaceEngine',
      copy: '실시간 얼굴 인식 기반 인증 및 보안 운영 엔진입니다.',
      features: ['실시간 비전 처리', '인증 정확도 최적화', '현장 시스템 연동'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 110,
      span: 1,
      industry: '보안, 출입관리',
      period: '4-8주 적용',
      integration: '카메라, 출입통제 시스템',
      tags: ['Vision', 'Face ID', 'Security'],
    },
    {
      id: 'ai-catvton',
      group: 'ai',
      badge: 'AI',
      title: 'CatVTON 가상 피팅',
      copy: '가상 착용 시뮬레이션으로 리테일 고객 경험을 혁신합니다.',
      features: ['의류 가상 피팅', '실시간 렌더링', '전환율 개선'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 120,
      span: 1,
      industry: '패션 리테일',
      period: '3-6주 적용',
      integration: '상품 DB, 이미지 처리 API',
      tags: ['Try-on', 'Retail AI', 'CV'],
    },
    {
      id: 'ai-construction',
      group: 'ai',
      badge: 'AI',
      title: '건설 하자보수 검증 플랫폼',
      copy: '검수 증빙과 검증 정확도를 높이는 산업 특화 AI입니다.',
      features: ['현장 데이터 수집', '하자 검증 자동화', '보고서 생성'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 130,
      span: 1,
      industry: '건설',
      period: '6-10주 구축',
      integration: '현장 앱, 보고 시스템',
      tags: ['Inspection', 'Construction', 'QA'],
    },
    {
      id: 'ai-ruview',
      group: 'ai',
      badge: 'AI',
      title: 'RuView',
      copy: 'WiFi 기반 비접촉 생체 신호 감지 솔루션입니다.',
      features: ['비접촉 모니터링', '실시간 데이터 분석', '현장 적용성 강화'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 140,
      span: 1,
      industry: '헬스케어, 모니터링',
      period: '4-8주 적용',
      integration: '센서/네트워크 장치, 대시보드',
      tags: ['WiFi Sensing', 'Bio Signal', 'Realtime'],
    },
    {
      id: 'ai-moonshine',
      group: 'ai',
      badge: 'AI',
      title: 'Moonshine 음성 인식',
      copy: '초경량 온디바이스 음성 인식 엔진입니다.',
      features: ['저지연 인식', '엣지 디바이스 최적화', '프라이버시 강화'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 150,
      span: 1,
      industry: '모바일, IoT',
      period: '2-5주 적용',
      integration: '디바이스 SDK, 명령 처리 서버',
      tags: ['Speech', 'On-device', 'Edge'],
    },
    {
      id: 'ai-autoresearch',
      group: 'ai',
      badge: 'AI',
      title: 'Autoresearch',
      copy: '자율 연구 에이전트 기반 분석 자동화 솔루션입니다.',
      features: ['리서치 자동화', '지식 요약/정리', '업무 생산성 향상'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 160,
      span: 1,
      industry: 'R&D, 전략기획',
      period: '2-4주 적용',
      integration: '문서 저장소, 검색 API',
      tags: ['Agent', 'Research', 'Knowledge'],
    },
    {
      id: 'ai-tennis-coaching',
      group: 'ai',
      badge: 'AI',
      title: 'AI Tennis Coaching 시스템',
      copy: '실시간 포즈 추정으로 스윙을 분석하고 코칭 리포트를 제공하는 AI 코칭 시스템입니다.',
      features: ['스윙 자세 추정', '프로 선수 동작 비교', '코칭 리포트 자동 생성'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 161,
      span: 2,
      industry: '스포츠 테크, 교육',
      period: '4-7주 적용',
      integration: '카메라 입력, 분석 엔진, 리포트 대시보드',
      tags: ['Sports AI', 'Pose Estimation', 'Coaching'],
    },
    {
      id: 'ai-workflow-engine',
      group: 'ai',
      badge: 'AI',
      title: '워크플로우 자동화 엔진',
      copy: '반복 업무를 규칙/AI로 자동 처리하는 워크플로우 오케스트레이션 엔진입니다.',
      features: ['업무 플로우 정의', '이벤트 기반 자동 실행', '처리 이력 추적'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 162,
      span: 1,
      industry: '기업 운영, 백오피스',
      period: '3-6주 적용',
      integration: '업무 시스템 API, 메시지 큐',
      tags: ['Workflow', 'Automation', 'Engine'],
    },
    {
      id: 'ai-worldmonitor',
      group: 'ai',
      badge: 'AI',
      title: 'WorldMonitor 글로벌 이벤트 모니터링',
      copy: '글로벌 이슈를 수집/분석해 중요 이벤트를 모니터링하는 시스템입니다.',
      features: ['실시간 이벤트 수집', '이슈 분류/요약', '알림 대시보드 제공'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 163,
      span: 1,
      industry: '전략, 리스크 관리',
      period: '3-5주 적용',
      integration: '뉴스/데이터 소스 API, 알림 채널',
      tags: ['Monitoring', 'Global', 'Alert'],
    },
    {
      id: 'ai-smartpathfinder',
      group: 'ai',
      badge: 'AI',
      title: 'SmartPathFinder AI 경로 탐색',
      copy: '실시간 조건을 반영해 최적 경로를 계산하는 AI 내비게이션 시스템입니다.',
      features: ['실시간 경로 계산', '혼잡도 반영 최적화', '상황별 경로 추천'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 164,
      span: 1,
      industry: '물류, 시설 운영',
      period: '4-7주 구축',
      integration: '지도 엔진, 위치 데이터, 운영 서버',
      tags: ['Routing', 'Navigation', 'Optimization'],
    },
    {
      id: 'ai-cafenlu',
      group: 'ai',
      badge: 'AI',
      title: 'CafeNlu 키오스크 자연어 이해',
      copy: '카페 키오스크 주문 문맥을 이해하는 도메인 특화 자연어 이해 모델입니다.',
      features: ['주문 의도 파악', '메뉴 엔티티 추출', '키오스크 주문 연동'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 165,
      span: 1,
      industry: '외식, 키오스크',
      period: '2-5주 적용',
      integration: '주문 시스템, NLU API',
      tags: ['NLU', 'Kiosk', 'Cafe'],
    },
    {
      id: 'ai-fitting-system',
      group: 'ai',
      badge: 'AI',
      title: 'AI 피팅 시스템',
      copy: '매장 키오스크와 온라인 채널에서 공통으로 쓰는 AI 피팅 솔루션입니다.',
      features: ['오프라인 키오스크 연동', '온라인 체험 모듈', '추천 정확도 향상'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 166,
      span: 1,
      industry: '패션 리테일',
      period: '3-6주 적용',
      integration: '상품 DB, 추천 엔진',
      tags: ['Fitting', 'Retail', 'Experience'],
    },
    {
      id: 'ai-remote-desktop-kiosk',
      group: 'ai',
      badge: 'AI',
      title: 'RemoteDesktop 원격 키오스크 관리',
      copy: '원격 데스크톱 기반으로 현장 키오스크를 중앙 관리하는 솔루션입니다.',
      features: ['원격 장애 대응', '배포/업데이트 관리', '운영 상태 모니터링'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 167,
      span: 1,
      industry: '현장 운영, 인프라',
      period: '3-6주 구축',
      integration: '원격 제어 서버, 단말 에이전트',
      tags: ['Remote Ops', 'Desktop', 'Kiosk'],
    },
    {
      id: 'ai-kiosk-agent-server',
      group: 'ai',
      badge: 'AI',
      title: '제어 서버 + 키오스크 에이전트',
      copy: '중앙 제어 서버와 현장 에이전트 구조로 대규모 키오스크를 안정 운영합니다.',
      features: ['중앙 제어 아키텍처', '에이전트 상태 동기화', '원격 정책 배포'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 168,
      span: 1,
      industry: '키오스크 인프라',
      period: '4-8주 구축',
      integration: '제어 서버, 단말 에이전트, 모니터링',
      tags: ['Control', 'Agent', 'Infrastructure'],
    },
    {
      id: 'airport-oneid',
      group: 'airport',
      badge: 'Airport',
      title: 'One ID 스마트 탑승',
      copy: '생체 정보 기반 탑승 수속 간소화 시스템입니다.',
      features: ['KAC One ID 확대 구축', '체크인 동선 단축', '탑승 경험 개선'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 170,
      span: 2,
      industry: '공항',
      period: '8-12주 단계 도입',
      integration: '인증 단말, 출입 게이트',
      tags: ['One ID', 'Biometric', 'Airport'],
    },
    {
      id: 'airport-immsec',
      group: 'airport',
      badge: 'Airport',
      title: 'Immsec 보안 게이트',
      copy: '공항 보안 게이트 인증 및 통과 프로세스를 최적화합니다.',
      features: ['신분 확인 단말 연동', '게이트 운영 효율화', '보안 수준 강화'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 180,
      span: 1,
      industry: '공항 보안',
      period: '6-10주 구축',
      integration: '게이트 장비, 관제 서버',
      tags: ['Security Gate', 'ID Check', 'Control'],
    },
    {
      id: 'airport-transfer',
      group: 'airport',
      badge: 'Airport',
      title: '국제선 환승 시스템',
      copy: '환승객 흐름을 빠르고 안전하게 처리하는 공항 특화 솔루션입니다.',
      features: ['환승 동선 최적화', '절차 자동 안내', '혼잡도 완화'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 190,
      span: 1,
      industry: '국제선 운영',
      period: '5-9주 구축',
      integration: '환승 시스템, 안내 단말',
      tags: ['Transfer', 'Passenger Flow', 'Guide'],
    },
    {
      id: 'airport-idterminal',
      group: 'airport',
      badge: 'Airport',
      title: '신분확인 단말',
      copy: '탑승객 인증을 위한 고신뢰 단말 솔루션입니다.',
      features: ['신원 인증 정확도 향상', '장비 연동성 확보', '운영 안정성 강화'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 200,
      span: 1,
      industry: '공항 인증',
      period: '4-7주 적용',
      integration: '인증 서버, 단말 펌웨어',
      tags: ['ID', 'Terminal', 'Reliability'],
    },
    {
      id: 'airport-bagdrop',
      group: 'airport',
      badge: 'Airport',
      title: 'Self Bag Drop 관제 시스템',
      copy: '셀프 수하물 위탁 장비의 운영 상태를 통합 관제합니다.',
      features: ['장비 상태 모니터링', '장애 대응 속도 개선', '운영 리포트 제공'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 210,
      span: 1,
      industry: '수하물 운영',
      period: '5-8주 구축',
      integration: 'Bag Drop 장비, 관제 대시보드',
      tags: ['Baggage', 'Monitoring', 'Ops'],
    },
    {
      id: 'airport-bagmeasure',
      group: 'airport',
      badge: 'Airport',
      title: '수하물 측정 장비 운영',
      copy: '수하물 규격 측정 및 처리 효율을 높이는 운영 시스템입니다.',
      features: ['측정 자동화', '처리 속도 개선', '운영 데이터 기록'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 220,
      span: 1,
      industry: '수하물 처리',
      period: '4-7주 적용',
      integration: '측정 장비, 운영 DB',
      tags: ['Measurement', 'Automation', 'Data'],
    },
    {
      id: 'airport-boardingauto',
      group: 'airport',
      badge: 'Airport',
      title: '무인 탑승권 발급 자동화',
      copy: '탑승권 발급 프로세스를 셀프 서비스로 전환합니다.',
      features: ['무인 발급 키오스크 연계', '대기시간 단축', '운영비 절감'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 230,
      span: 1,
      industry: '여객 서비스',
      period: '4-6주 적용',
      integration: '발권 시스템, 키오스크',
      tags: ['Ticketing', 'Self Service', 'Queue'],
    },
    {
      id: 'airport-bagauto',
      group: 'airport',
      badge: 'Airport',
      title: '수하물 위탁 자동화',
      copy: '수하물 접수부터 처리까지 자동화하는 공항 운영 솔루션입니다.',
      features: ['셀프 위탁 프로세스', '오류율 감소', '처리량 향상'],
      ctaLabel: '상담 요청',
      ctaStyle: 'primary',
      priority: 240,
      span: 1,
      industry: '공항 운영',
      period: '5-8주 구축',
      integration: '위탁 장비, BHS 연계',
      tags: ['Bag Drop', 'Automation', 'Airport'],
    },
    {
      id: 'enterprise-scale',
      group: 'all',
      badge: 'Enterprise',
      title: 'Scale Program',
      copy: '50+ 제품 도입을 위한 통합 아키텍처 설계 및 단계별 전환 프로그램입니다.',
      features: ['제품군 로드맵', '통합 SSO/권한 모델', '24/7 운영지원'],
      ctaLabel: '제안서 받기',
      ctaStyle: 'ghost',
      priority: 999,
      span: 4,
      industry: '다사업 통합 조직',
      period: '분기 단위 확대',
      integration: 'SSO, 권한, 통합 모니터링',
      tags: ['Scale-up', 'Governance', 'Support'],
    },
  ];

  function clone(value) {
    return JSON.parse(JSON.stringify(value));
  }

  function normalizeCard(card) {
    return {
      id: String(card.id || `card-${Date.now()}`),
      group: card.group || 'all',
      badge: card.badge || 'Package',
      title: card.title || '제목 없음',
      copy: card.copy || '',
      features: Array.isArray(card.features) ? card.features : [],
      ctaLabel: card.ctaLabel || '상담 요청',
      ctaStyle: card.ctaStyle === 'ghost' ? 'ghost' : 'primary',
      priority: Number.isFinite(Number(card.priority)) ? Number(card.priority) : 999,
      span: Math.max(1, Math.min(4, Number(card.span) || 1)),
      industry: card.industry || '',
      period: card.period || '',
      integration: card.integration || '',
      tags: Array.isArray(card.tags) ? card.tags : [],
    };
  }

  function sortCards(cards) {
    return cards
      .slice()
      .map(normalizeCard)
      .sort((a, b) => a.priority - b.priority || a.title.localeCompare(b.title, 'ko'));
  }

  function getCards() {
    try {
      const raw = localStorage.getItem(STORAGE_KEY);
      if (!raw) {
        return sortCards(defaultCards);
      }
      const parsed = JSON.parse(raw);
      if (!Array.isArray(parsed) || parsed.length === 0) {
        return sortCards(defaultCards);
      }

      const stored = sortCards(parsed);
      const defaults = sortCards(defaultCards);
      const existingIds = new Set(stored.map((card) => card.id));
      const merged = [...stored];

      // Keep user edits while automatically appending newly added default cards.
      defaults.forEach((card) => {
        if (!existingIds.has(card.id)) {
          merged.push(card);
        }
      });

      return sortCards(merged);
    } catch (_error) {
      return sortCards(defaultCards);
    }
  }

  function saveCards(cards) {
    const normalized = sortCards(cards);
    localStorage.setItem(STORAGE_KEY, JSON.stringify(normalized));
    return normalized;
  }

  function resetCards() {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(sortCards(defaultCards)));
    return sortCards(defaultCards);
  }

  window.BitHappenCardStore = {
    key: STORAGE_KEY,
    getCards,
    saveCards,
    resetCards,
    defaultCards: clone(defaultCards),
  };
})();
